FROM nginx:latest
RUN rm /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
# RUN rm -rf /usr/share/nginx/html
COPY /etc/letsencrypt/live/engineerbeard.com/fullchain.pem /etc/nginx/fullchain.pem
COPY /etc/letsencrypt/live/engineerbeard.com/privkey.pem /etc/nginx/privkey.pem